/root/
    /home/
        index.html
    /basic/
        index.html
    /cart/
        index.html
    /contact/
        index.html
    /cookies/
        index.html
    /dactenergy/
        index.html
    /error/
        index.html
    /products/
        index.html
    /team/
        index.html
/script.js 